CREATE TABLE DeepSpace
(
  eventName varchar(20),
  matchNumber int,
  alliance varchar(4),
  teamNumber int,
  driverPosition int,
  noShow boolean,
  startPos int,
  sandStorm_crossLine boolean,
  sandStorm_deadBot boolean,
  sandStorm_rocket_level1_hatch int,
  sandStorm_rocket_level1_cargo int,
  sandStorm_rocket_level2_hatch int,
  sandStorm_rocket_level2_cargo int,
  sandStorm_rocket_level3_hatch int,
  sandStorm_rocket_level3_cargo int,
  sandStorm_ship_hatch int,
  sandStorm_ship_cargo int,
  sandStorm_retrieved_hatch int,
  sandStorm_retrieved_cargo int,
  sandStorm_dropped_hatch int,
  sandStorm_dropped_cargo int,
  teleOp_obscured_rocket_level1_hatch int,
  -- teleOp_obscured_rocket_level1_cargo int,
  teleOp_obscured_rocket_level2_hatch int,
  -- teleOp_obscured_rocket_level2_cargo int,
  teleOp_obscured_rocket_level3_hatch int,
  -- teleOp_obscured_rocket_level3_cargo int,
  teleOp_obscured_ship_hatch int,
  teleOp_obscured_ship_cargo int,
  teleOp_unobscured_rocket_level1_hatch int,
  teleOp_unobscured_rocket_level1_cargo int,
  teleOp_unobscured_rocket_level2_hatch int,
  teleOp_unobscured_rocket_level2_cargo int,
  teleOp_unobscured_rocket_level3_hatch int,
  teleOp_unobscured_rocket_level3_cargo int,
  teleOp_unobscured_ship_hatch int,
  teleOp_unobscured_ship_cargo int,
  teleOp_retrieved_loading_hatch int,
  teleOp_retrieved_loading_cargo int,
  teleOp_retrieved_floor_hatch int,
  teleOp_retrieved_floor_cargo int,
  teleOp_dropped_hatch int,
  teleOp_dropped_cargo int,
  teleOp_climbLevel int,
  teleOp_assistedClimb boolean,
  teleOp_recievedClimb boolean,

  PRIMARY KEY	(eventName, teamNumber, matchNumber)
);
